export const GET_ORGANISATIONS = 'GET_ORGANISATION';
export const GET_ORGANISATIONS_SUCCESS = 'GET_ORGANISATIONS_SUCCESS';
export const TOGGLE_SIDER = 'TOGGLE_SIDER';

//Spaces
export const GET_SPACES_SUCCESS = 'GET_SPACES_SUCCESS';
export const GET_SPACES_FAILURE = 'GET_SPACES_FAILURE';
export const ADD_SPACE = 'ADD_SPACE';
export const LOADING_SPACES = 'LOADING_SPACES';
export const ADD_SPACE_SUCCESS = 'ADD_SPACE_SUCCESS';
export const ADD_SPACE_FAILURE = 'ADD_SPACE_SUCCESS';
