//Actions
export const ADD_SPACE_PERMISSION = 'ADD_SPACE_PERMISSION';
export const ADD_SPACE_PERMISSIONS = 'ADD_SPACE_PERMISSIONS';
export const ADD_SPACE_PERMISSIONS_REQUEST = 'ADD_SPACE_PERMISSIONS_REQUEST';
export const RESET_SPACE_PERMISSIONS = 'RESET_SPACE_PERMISSIONS';
export const SET_SPACE_PERMISSIONS_LOADING = 'SET_SPACE_PERMISSIONS_LOADING';

//API
export const SPACE_PERMISSIONS_API = '/core/permissions/spaces';
