//Actions
export const GET_CLAIMANTS_SUCCESS = 'GET_CLAIMANTS_SUCCESS';
export const GET_CLAIMANTS_FAILURE = 'GET_CLAIMANTS_FAILURE';
export const GET_CLAIMANT_SUCCESS = 'GET_CLAIMANT_SUCCESS';
export const GET_CLAIMANT_FAILURE = 'GET_CLAIMANT_FAILURE';
export const ADD_CLAIMANT_SUCCESS = 'ADD_CLAIMANT_SUCCESS';
export const ADD_CLAIMANT_FAILURE = 'ADD_CLAIMANT_FAILURE';
export const UPDATE_CLAIMANT_SUCCESS = 'UPDATE_CLAIMANT_SUCCESS';
export const UPDATE_CLAIMANT_FAILURE = 'UPDATE_CLAIMANT_FAILURE';
export const DELETE_CLAIMANT_SUCCESS = 'DELETE_CLAIMANT_SUCCESS';
export const DELETE_CLAIMANT_FAILURE = 'DELETE_CLAIMANT_FAILURE';
export const LOADING_CLAIMANTS = 'LOADING_CLAIMANTS';
export const ADD_CLAIMANTS = 'ADD_CLAIMANTS';

//API
export const API_GET_CLAIMANTS = '/factcheck/claimants';
export const API_ADD_CLAIMANT = '/factcheck/claimants';
