//Actions
export const GET_FACT_CHECKS_SUCCESS = 'GET_FACT_CHECKS_SUCCESS';
export const GET_FACT_CHECKS_FAILURE = 'GET_FACT_CHECKS_FAILURE';
export const GET_FACT_CHECK_SUCCESS = 'GET_FACT_CHECK_SUCCESS';
export const GET_FACT_CHECK_FAILURE = 'GET_FACT_CHECK_FAILURE';
export const ADD_FACT_CHECK_SUCCESS = 'ADD_FACT_CHECK_SUCCESS';
export const ADD_FACT_CHECK_FAILURE = 'ADD_FACT_CHECK_FAILURE';
export const UPDATE_FACT_CHECK_SUCCESS = 'UPDATE_FACT_CHECK_SUCCESS';
export const UPDATE_FACT_CHECK_FAILURE = 'UPDATE_FACT_CHECK_FAILURE';
export const DELETE_FACT_CHECK_SUCCESS = 'DELETE_FACT_CHECK_SUCCESS';
export const DELETE_FACT_CHECK_FAILURE = 'DELETE_FACT_CHECK_FAILURE';
export const LOADING_FACT_CHECKS = 'LOADING_FACT_CHECKS';

//API
export const API_GET_FACT_CHECKS = '/factcheck/factchecks';
export const API_ADD_FACT_CHECK = '/factcheck/factchecks';
