//Actions
export const GET_FORMATS_SUCCESS = 'GET_FORMATS_SUCCESS';
export const GET_FORMATS_FAILURE = 'GET_FORMATS_FAILURE';
export const ADD_FORMAT_SUCCESS = 'ADD_FORMAT_SUCCESS';
export const ADD_FORMAT_FAILURE = 'ADD_FORMAT_FAILURE';
export const UPDATE_FORMAT_SUCCESS = 'UPDATE_FORMAT_SUCCESS';
export const UPDATE_FORMAT_FAILURE = 'UPDATE_FORMAT_FAILURE';
export const DELETE_FORMAT_SUCCESS = 'DELETE_FORMAT_SUCCESS';
export const DELETE_FORMAT_FAILURE = 'DELETE_FORMAT_FAILURE';
export const LOADING_FORMATS = 'LOADING_FORMATS';

//API
export const API_GET_FORMATS = '/core/formats';
export const API_ADD_FORMAT = '/core/formats';
