//Actions
export const ADD_ORGANISATION_PERMISSION = 'ADD_ORGANISATION_PERMISSION';
export const ADD_ORGANISATION_PERMISSIONS = 'ADD_ORGANISATION_PERMISSIONS';
export const ADD_ORGANISATION_PERMISSIONS_REQUEST = 'ADD_ORGANISATION_PERMISSIONS_REQUEST';
export const RESET_ORGANISATION_PERMISSIONS = 'RESET_ORGANISATION_PERMISSIONS';
export const SET_ORGANISATION_PERMISSIONS_LOADING = 'SET_ORGANISATION_PERMISSIONS_LOADING';

//API
export const ORGANISATION_PERMISSIONS_API = '/core/organisations/permissions';
