//Actions
export const ADD_ORGANISATION_REQUEST = 'ADD_ORGANISATION_REQUEST';
export const ADD_ORGANISATION_REQUESTS = 'ADD_ORGANISATION_REQUESTS';
export const ADD_ORGANISATION_REQUESTS_REQUEST = 'ADD_ORGANISATION_REQUESTS_REQUEST';
export const RESET_ORGANISATION_REQUESTS = 'RESET_ORGANISATION_REQUESTS';
export const SET_ORGANISATION_REQUESTS_LOADING = 'SET_ORGANISATION_REQUESTS_LOADING';

//API
export const ORGANISATION_REQUESTS_API = '/core/requests/organisation-permissions';
export const ORGANISATION_REQUESTS_CREATE_API = '/core/permissions/organisations/request';
