export const ADD_PERMISSIONS_REQUEST = 'ADD_PERMISSIONS_REQUEST';
export const SET_PERMISSIONS_LOADING = 'SET_PERMISSIONS_LOADING';
export const ADD_PERMISSIONS = 'ADD_PERMISSIONS';
//API
export const PERMISSIONS_API = '/core/users/';
