package main

import (
	"github.com/factly/dega-server/cmd"

	_ "github.com/factly/dega-server/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Dega API
// @version 1.0
// @description Dega server API

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:7789
// @BasePath /
func main() {
	cmd.Execute()
}
