//Actions
export const ADD_SACH_FACT_CHECKS = 'ADD_SACH_FACT_CHECKS';
export const ADD_SACH_FACT_CHECKS_REQUEST = 'ADD_SACH_FACT_CHECKS_REQUEST';
export const SET_SACH_FACT_CHECKS_LOADING = 'SET_SACH_FACT_CHECKS_LOADING';

//API
export const SACH_FACT_CHECKS_API = '/search';
