//Actions
export const ADD_SPACE_REQUEST = 'ADD_SPACE_REQUEST';
export const ADD_SPACE_REQUESTS = 'ADD_SPACE_REQUESTS';
export const ADD_SPACE_REQUESTS_REQUEST = 'ADD_SPACE_REQUESTS_REQUEST';
export const RESET_SPACE_REQUESTS = 'RESET_SPACE_REQUESTS';
export const SET_SPACE_REQUESTS_LOADING = 'SET_SPACE_REQUESTS_LOADING';

//API
export const SPACE_REQUESTS_API = '/core/requests/spaces';
export const SPACE_REQUESTS_CREATE_API = '/core/requests/spaces';
