//Actions
export const ADD_WEBHOOKLOG = 'ADD_WEBHOOKLOG';
export const ADD_WEBHOOKLOGS = 'ADD_WEBHOOKLOGS';
export const ADD_WEBHOOKLOGS_REQUEST = 'ADD_WEBHOOKLOGS_REQUEST';
export const RESET_WEBHOOKLOGS = 'RESET_WEBHOOKLOGS';
export const SET_WEBHOOKLOGS_LOADING = 'SET_WEBHOOKLOGS_LOADING';