// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type PostFilter struct {
	Slugs []string `json:"slugs,omitempty"`
	Ids   []string `json:"ids,omitempty"`
}

type Query struct {
}

type SearchResult struct {
	Posts      []*Post     `json:"posts,omitempty"`
	Categories []*Category `json:"categories,omitempty"`
	Tags       []*Tag      `json:"tags,omitempty"`
	Claims     []*Claim    `json:"claims,omitempty"`
	Claimants  []*Claimant `json:"claimants,omitempty"`
	Ratings    []*Rating   `json:"ratings,omitempty"`
	Media      []*Medium   `json:"media,omitempty"`
}
