FROM golang:1.20-alpine
RUN apk add ca-certificates

RUN apk add gcc musl-dev
WORKDIR /app
COPY dega-api .

# Run the binary program produced by `go install`
ENTRYPOINT ["/app/dega-api"]
CMD ["serve"]