name: Release CI
on:
  push:
    tags:
      - '*'

jobs:
  release:
    uses: factly/gopie-ee/.github/workflows/docker-build-push.yaml@develop
    with:
      tags: asia-south1-docker.pkg.dev/factly-prod/dega/studio:${{ github.ref_name }}
      context: studio
      dockerfile: studio/Dockerfile.prod
    permissions:
      contents: read
      id-token: write